package eu.nyerel.panda.agent.instrumentation.jdbc.model;

import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * @author Rastislav Papp (rastislav.papp@gmail.com)
 */
public interface ConnectionCreatePreparedStatement {

	PreparedStatement prepareStatement(String sql) throws SQLException;
	PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;
	PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;
	PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
	PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException;
	PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException;

}